---
# tasks file for gitlab
- name: Install dependency
  apt:
    pkg:
      - curl
      - openssh-server
      - ca-certificates
      - perl
      - postfix
    update_cache: yes
    state: present

- name: Download instalation script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh

- name: Run the script
  command: bash /tmp/script.deb.sh

- name: Install GitLab
  apt: name=gitlab-ce update_cache=yes state=present


