---
# tasks file for puppet
# Check the minimum hardware requeriments in this documment: https://docs.gitlab.com/ee/install/requirements.html

- name: Check if OS is Debian Family
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

#- name: Check if OS is RedHat Family
#  include_tasks: redhat.yml
#  when: ansible_os_family == "RedHat"