galaxy_info:
  author: Romain Cabassot
  description: Installs OCS inventory agent from a package repository and can setup the cron to launch the inventory.
  #company: your company (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: BSD

  min_ansible_version: 1.9

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If travis integration is cofigured, only notification for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  platforms:
  - name: Ubuntu
    versions:
  #  - all
  #  - lucid
  #  - maverick
  #  - natty
  #  - oneiric
  #  - precise
  #  - quantal
  #  - raring
  #  - saucy
    - trusty
  #  - utopic
  #  - vivid
  #  - wily
    - xenial
  - name: Debian
    versions:
  #  - all
  #  - etch
    - jessie
  #  - lenny
  #  - sid
  #  - squeeze
    - stretch
  #  - wheezy
  - name: EL
    versions:
  #  - all
  #  - 5
    - 6
    - 7
  
  galaxy_tags:
  - ocs
  - inventory
  - ocsinventory
  - agent

  dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
