---
all:
  children:
#WINDOWS
    windows_ad:
      hosts:
        192.168.1.29:
    windows_ts:
      hosts:
    win:
      children:
        windows_ad:
        windows_ts:
      vars:
        ansible_user: administrator
        ansible_password: "{{ vault_windows_administrator_password }}"
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
#LINUX
    linux_db:
      hosts:
        192.168.1.150:  
    linux_web:
      hosts:
    devops:
      hosts:
    automation:
      hosts:
    docker:
      hosts:
        192.168.10.150:
        #192.168.1.150:
        #  ansible_user: vagrant
        #  ansible_ssh_private_key_file: ~/devops/vagrant/.vagrant/machines/debian10/virtualbox/private_key
        #  ansible_connection: ssh
    unifi:
      hosts:
    kubernetes_master:
      hosts:
    kubernetes_worker:
      hosts:
    raspberrypi:
      hosts:
        192.168.10.102:
    zabbix:
      hosts:
        192.168.10.150:
    
    tux:
      children:
        #linux_db:
        #linux_web:
        raspberrypi:
        docker:
        zabbix:
      vars:
        #ansible_user: vagrant
        ansible_user: vagrant
        #ansible_ssh_private_key_file: ~/devops/vagrant/.vagrant/machines/debian10/virtualbox/private_key
        ansible_ssh_private_key_file: ~/devops/vagrant/.vagrant/machines/debian9/virtualbox/private_key
        #ansible_ssh_private_key_file: ~/devops/vagrant/.vagrant/machines/centos8/virtualbox/private_key
        #ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_connection: ssh
        ansible_become: yes
        
